<?php
$data = array (
  325 => 
  array (
    'cat_id' => '325',
    'cat_name' => '家具城',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '325',
    'name' => '家具城',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '卧室',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => '84',
    'level' => 1,
    'id' => '4',
    'name' => '卧室',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => '穿衣镜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '228',
    'name' => '穿衣镜',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '衣柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '63',
    'level' => 2,
    'id' => '74',
    'name' => '衣柜',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '床',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '99',
    'level' => 2,
    'id' => '23',
    'name' => '床',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '床尾凳',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '88',
    'name' => '床尾凳',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '定制衣柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '226',
    'name' => '定制衣柜',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '床垫',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 2,
    'id' => '24',
    'name' => '床垫',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => '斗柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '227',
    'name' => '斗柜',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '梳妆台',
    'measure_unit' => '张',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 2,
    'id' => '69',
    'name' => '梳妆台',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '床头柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '25',
    'name' => '床头柜',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => '客厅',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => '1',
    'level' => 1,
    'id' => '229',
    'name' => '客厅',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => '电视柜',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '39',
    'level' => 2,
    'id' => '231',
    'name' => '电视柜',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '真皮沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 2,
    'id' => '235',
    'name' => '真皮沙发',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => '酒柜',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '232',
    'name' => '酒柜',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
    'level' => 2,
    'id' => '230',
    'name' => '沙发',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '休闲椅',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '238',
    'name' => '休闲椅',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => '茶几',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '62',
    'level' => 2,
    'id' => '233',
    'name' => '茶几',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => '布艺沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '48',
    'level' => 2,
    'id' => '237',
    'name' => '布艺沙发',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '转角沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '239',
    'name' => '转角沙发',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => '鞋柜',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '234',
    'name' => '鞋柜',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '组合沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '236',
    'name' => '组合沙发',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => '餐厅',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '240',
    'name' => '餐厅',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '圆餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '245',
    'name' => '圆餐桌',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '242',
    'name' => '餐椅',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '折叠餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '247',
    'name' => '折叠餐桌',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '长餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '246',
    'name' => '长餐桌',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '餐边柜',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '243',
    'name' => '餐边柜',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '餐桌椅套餐',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '244',
    'name' => '餐桌椅套餐',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => '餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 2,
    'id' => '241',
    'name' => '餐桌',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => '书房',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '248',
    'name' => '书房',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '实木书桌',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '251',
    'name' => '实木书桌',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => '书柜/书架',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '252',
    'name' => '书柜/书架',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => '书桌/工作台',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '249',
    'name' => '书桌/工作台',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => '书椅/转椅',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '253',
    'name' => '书椅/转椅',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '转角书桌',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '250',
    'name' => '转角书桌',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '书房套装',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '254',
    'name' => '书房套装',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '儿童房',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '255',
    'name' => '儿童房',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '儿童桌',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '260',
    'name' => '儿童桌',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => '儿童床头柜',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '258',
    'name' => '儿童床头柜',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => '儿童床',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '256',
    'name' => '儿童床',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => '双层床',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '262',
    'name' => '双层床',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => '儿童衣柜',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '259',
    'name' => '儿童衣柜',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => '儿童椅',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '261',
    'name' => '儿童椅',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '儿童床垫',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '257',
    'name' => '儿童床垫',
  ),
  326 => 
  array (
    'cat_id' => '326',
    'cat_name' => '家居城',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '326',
    'name' => '家居城',
  ),
  277 => 
  array (
    'cat_id' => '277',
    'cat_name' => '灯饰照明',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '277',
    'name' => '灯饰照明',
  ),
  282 => 
  array (
    'cat_id' => '282',
    'cat_name' => '落地灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '282',
    'name' => '落地灯',
  ),
  279 => 
  array (
    'cat_id' => '279',
    'cat_name' => '壁灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '279',
    'name' => '壁灯',
  ),
  283 => 
  array (
    'cat_id' => '283',
    'cat_name' => 'LED/光源',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '283',
    'name' => 'LED/光源',
  ),
  280 => 
  array (
    'cat_id' => '280',
    'cat_name' => '吸顶灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '63',
    'level' => 2,
    'id' => '280',
    'name' => '吸顶灯',
  ),
  281 => 
  array (
    'cat_id' => '281',
    'cat_name' => '台灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '79',
    'level' => 2,
    'id' => '281',
    'name' => '台灯',
  ),
  278 => 
  array (
    'cat_id' => '278',
    'cat_name' => '吊顶',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '40',
    'level' => 2,
    'id' => '278',
    'name' => '吊顶',
  ),
  298 => 
  array (
    'cat_id' => '298',
    'cat_name' => '厨房用品',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '298',
    'name' => '厨房用品',
  ),
  299 => 
  array (
    'cat_id' => '299',
    'cat_name' => '厨盆/水槽',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 2,
    'id' => '299',
    'name' => '厨盆/水槽',
  ),
  300 => 
  array (
    'cat_id' => '300',
    'cat_name' => '厨房挂件',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '300',
    'name' => '厨房挂件',
  ),
  292 => 
  array (
    'cat_id' => '292',
    'cat_name' => '卫浴用品',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => '1',
    'level' => 1,
    'id' => '292',
    'name' => '卫浴用品',
  ),
  296 => 
  array (
    'cat_id' => '296',
    'cat_name' => '花洒',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '35',
    'level' => 2,
    'id' => '296',
    'name' => '花洒',
  ),
  293 => 
  array (
    'cat_id' => '293',
    'cat_name' => '浴室柜',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '56',
    'level' => 2,
    'id' => '293',
    'name' => '浴室柜',
  ),
  297 => 
  array (
    'cat_id' => '297',
    'cat_name' => '座便器',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '58',
    'level' => 2,
    'id' => '297',
    'name' => '座便器',
  ),
  295 => 
  array (
    'cat_id' => '295',
    'cat_name' => '浴缸',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '295',
    'name' => '浴缸',
  ),
  321 => 
  array (
    'cat_id' => '321',
    'cat_name' => '淋浴房',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '321',
    'name' => '淋浴房',
  ),
  284 => 
  array (
    'cat_id' => '284',
    'cat_name' => '生活电器',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '284',
    'name' => '生活电器',
  ),
  288 => 
  array (
    'cat_id' => '288',
    'cat_name' => '电视',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '288',
    'name' => '电视',
  ),
  285 => 
  array (
    'cat_id' => '285',
    'cat_name' => '冰箱',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '285',
    'name' => '冰箱',
  ),
  289 => 
  array (
    'cat_id' => '289',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '289',
    'name' => '热水器',
  ),
  286 => 
  array (
    'cat_id' => '286',
    'cat_name' => '洗衣机',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '286',
    'name' => '洗衣机',
  ),
  290 => 
  array (
    'cat_id' => '290',
    'cat_name' => '吸油烟机',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '290',
    'name' => '吸油烟机',
  ),
  287 => 
  array (
    'cat_id' => '287',
    'cat_name' => '空调',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '287',
    'name' => '空调',
  ),
  291 => 
  array (
    'cat_id' => '291',
    'cat_name' => '净水设备',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '291',
    'name' => '净水设备',
  ),
  525 => 
  array (
    'cat_id' => '525',
    'cat_name' => '油漆类',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '525',
    'name' => '油漆类',
  ),
  528 => 
  array (
    'cat_id' => '528',
    'cat_name' => '乳胶漆配件',
    'measure_unit' => '套',
    'parent_id' => '525',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '528',
    'name' => '乳胶漆配件',
  ),
  526 => 
  array (
    'cat_id' => '526',
    'cat_name' => '乳胶漆',
    'measure_unit' => '套',
    'parent_id' => '525',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '526',
    'name' => '乳胶漆',
  ),
  527 => 
  array (
    'cat_id' => '527',
    'cat_name' => '木器漆',
    'measure_unit' => '套',
    'parent_id' => '525',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '527',
    'name' => '木器漆',
  ),
  503 => 
  array (
    'cat_id' => '503',
    'cat_name' => '办公家具',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '503',
    'name' => '办公家具',
  ),
  270 => 
  array (
    'cat_id' => '270',
    'cat_name' => '办公家具',
    'measure_unit' => '套',
    'parent_id' => '503',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '270',
    'name' => '办公家具',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '办公桌',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '272',
    'name' => '办公桌',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => '办公沙发',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '271',
    'name' => '办公沙发',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => '办公椅',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '276',
    'name' => '办公椅',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '会议桌',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '273',
    'name' => '会议桌',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => '大班台',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '274',
    'name' => '大班台',
  ),
  275 => 
  array (
    'cat_id' => '275',
    'cat_name' => '文件柜',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '275',
    'name' => '文件柜',
  ),
  502 => 
  array (
    'cat_id' => '502',
    'cat_name' => '户外家具',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '502',
    'name' => '户外家具',
  ),
  263 => 
  array (
    'cat_id' => '263',
    'cat_name' => '户外家具',
    'measure_unit' => '套',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '263',
    'name' => '户外家具',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => '吊篮',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '266',
    'name' => '吊篮',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => '户外桌椅',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '264',
    'name' => '户外桌椅',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => '摇椅',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '269',
    'name' => '摇椅',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => '沙滩床',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '268',
    'name' => '沙滩床',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => '户外秋千',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '267',
    'name' => '户外秋千',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => '遮阳伞',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '265',
    'name' => '遮阳伞',
  ),
  507 => 
  array (
    'cat_id' => '507',
    'cat_name' => '定制家具',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '507',
    'name' => '定制家具',
  ),
  508 => 
  array (
    'cat_id' => '508',
    'cat_name' => '定制家具',
    'measure_unit' => '套',
    'parent_id' => '507',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '508',
    'name' => '定制家具',
  ),
  512 => 
  array (
    'cat_id' => '512',
    'cat_name' => '定制酒柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '512',
    'name' => '定制酒柜',
  ),
  509 => 
  array (
    'cat_id' => '509',
    'cat_name' => '定制橱柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '509',
    'name' => '定制橱柜',
  ),
  511 => 
  array (
    'cat_id' => '511',
    'cat_name' => '定制鞋柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '511',
    'name' => '定制鞋柜',
  ),
  513 => 
  array (
    'cat_id' => '513',
    'cat_name' => '定制储物柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '513',
    'name' => '定制储物柜',
  ),
  510 => 
  array (
    'cat_id' => '510',
    'cat_name' => '定制衣柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '510',
    'name' => '定制衣柜',
  ),
  506 => 
  array (
    'cat_id' => '506',
    'cat_name' => '墙纸地板',
    'measure_unit' => 'm2',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '506',
    'name' => '墙纸地板',
  ),
  301 => 
  array (
    'cat_id' => '301',
    'cat_name' => '墙面',
    'measure_unit' => '套',
    'parent_id' => '506',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '301',
    'name' => '墙面',
  ),
  577 => 
  array (
    'cat_id' => '577',
    'cat_name' => 'PVC墙纸',
    'measure_unit' => '',
    'parent_id' => '301',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '577',
    'name' => 'PVC墙纸',
  ),
  576 => 
  array (
    'cat_id' => '576',
    'cat_name' => '无纺布墙纸',
    'measure_unit' => '',
    'parent_id' => '301',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '576',
    'name' => '无纺布墙纸',
  ),
  302 => 
  array (
    'cat_id' => '302',
    'cat_name' => '墙布',
    'measure_unit' => '',
    'parent_id' => '301',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '27',
    'level' => 2,
    'id' => '302',
    'name' => '墙布',
  ),
  573 => 
  array (
    'cat_id' => '573',
    'cat_name' => '地面',
    'measure_unit' => '',
    'parent_id' => '506',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '573',
    'name' => '地面',
  ),
  574 => 
  array (
    'cat_id' => '574',
    'cat_name' => '实木地板',
    'measure_unit' => '',
    'parent_id' => '573',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '574',
    'name' => '实木地板',
  ),
  575 => 
  array (
    'cat_id' => '575',
    'cat_name' => '强化复合地板',
    'measure_unit' => '',
    'parent_id' => '573',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '575',
    'name' => '强化复合地板',
  ),
  303 => 
  array (
    'cat_id' => '303',
    'cat_name' => '强化实木地板',
    'measure_unit' => '',
    'parent_id' => '573',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '90',
    'level' => 2,
    'id' => '303',
    'name' => '强化实木地板',
  ),
  515 => 
  array (
    'cat_id' => '515',
    'cat_name' => '定制木门',
    'measure_unit' => '樘',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '515',
    'name' => '定制木门',
  ),
  504 => 
  array (
    'cat_id' => '504',
    'cat_name' => '五金配件',
    'measure_unit' => '套',
    'parent_id' => '515',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '504',
    'name' => '五金配件',
  ),
  307 => 
  array (
    'cat_id' => '307',
    'cat_name' => '家装五金',
    'measure_unit' => '套',
    'parent_id' => '504',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '307',
    'name' => '家装五金',
  ),
  308 => 
  array (
    'cat_id' => '308',
    'cat_name' => '开关插座',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 3,
    'id' => '308',
    'name' => '开关插座',
  ),
  309 => 
  array (
    'cat_id' => '309',
    'cat_name' => '锁具',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '309',
    'name' => '锁具',
  ),
  310 => 
  array (
    'cat_id' => '310',
    'cat_name' => '门吸',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '310',
    'name' => '门吸',
  ),
  530 => 
  array (
    'cat_id' => '530',
    'cat_name' => '钛金移门',
    'measure_unit' => '套',
    'parent_id' => '515',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '530',
    'name' => '钛金移门',
  ),
  516 => 
  array (
    'cat_id' => '516',
    'cat_name' => '套装门',
    'measure_unit' => '樘',
    'parent_id' => '515',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '516',
    'name' => '套装门',
  ),
  518 => 
  array (
    'cat_id' => '518',
    'cat_name' => '复合门',
    'measure_unit' => '樘',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '518',
    'name' => '复合门',
  ),
  517 => 
  array (
    'cat_id' => '517',
    'cat_name' => '实木门',
    'measure_unit' => '樘',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '517',
    'name' => '实木门',
  ),
  519 => 
  array (
    'cat_id' => '519',
    'cat_name' => '工艺门',
    'measure_unit' => '樘',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '519',
    'name' => '工艺门',
  ),
  514 => 
  array (
    'cat_id' => '514',
    'cat_name' => '瓷砖建材',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '514',
    'name' => '瓷砖建材',
  ),
  520 => 
  array (
    'cat_id' => '520',
    'cat_name' => '瓷砖类目',
    'measure_unit' => 'm2',
    'parent_id' => '514',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '520',
    'name' => '瓷砖类目',
  ),
  524 => 
  array (
    'cat_id' => '524',
    'cat_name' => '阳台瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '524',
    'name' => '阳台瓷砖',
  ),
  522 => 
  array (
    'cat_id' => '522',
    'cat_name' => '厨房瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '522',
    'name' => '厨房瓷砖',
  ),
  521 => 
  array (
    'cat_id' => '521',
    'cat_name' => '客厅瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '521',
    'name' => '客厅瓷砖',
  ),
  523 => 
  array (
    'cat_id' => '523',
    'cat_name' => '厕所瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '523',
    'name' => '厕所瓷砖',
  ),
  311 => 
  array (
    'cat_id' => '311',
    'cat_name' => '家纺家饰',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '311',
    'name' => '家纺家饰',
  ),
  312 => 
  array (
    'cat_id' => '312',
    'cat_name' => '床上用品',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '16',
    'goods_num' => 0,
    'level' => 1,
    'id' => '312',
    'name' => '床上用品',
  ),
  341 => 
  array (
    'cat_id' => '341',
    'cat_name' => '特惠套餐',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '341',
    'name' => '特惠套餐',
  ),
  354 => 
  array (
    'cat_id' => '354',
    'cat_name' => '夏凉被',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '354',
    'name' => '夏凉被',
  ),
  351 => 
  array (
    'cat_id' => '351',
    'cat_name' => '枕套',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '351',
    'name' => '枕套',
  ),
  348 => 
  array (
    'cat_id' => '348',
    'cat_name' => '被套',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '348',
    'name' => '被套',
  ),
  345 => 
  array (
    'cat_id' => '345',
    'cat_name' => '毛毯',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '345',
    'name' => '毛毯',
  ),
  342 => 
  array (
    'cat_id' => '342',
    'cat_name' => '床幔/蚊帐',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '342',
    'name' => '床幔/蚊帐',
  ),
  339 => 
  array (
    'cat_id' => '339',
    'cat_name' => '床品件套',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '339',
    'name' => '床品件套',
  ),
  352 => 
  array (
    'cat_id' => '352',
    'cat_name' => '凉席',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '352',
    'name' => '凉席',
  ),
  349 => 
  array (
    'cat_id' => '349',
    'cat_name' => '床笠',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '349',
    'name' => '床笠',
  ),
  346 => 
  array (
    'cat_id' => '346',
    'cat_name' => '床褥',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '346',
    'name' => '床褥',
  ),
  343 => 
  array (
    'cat_id' => '343',
    'cat_name' => '被芯',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '343',
    'name' => '被芯',
  ),
  340 => 
  array (
    'cat_id' => '340',
    'cat_name' => '记忆枕',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '340',
    'name' => '记忆枕',
  ),
  353 => 
  array (
    'cat_id' => '353',
    'cat_name' => '婚庆家纺',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '353',
    'name' => '婚庆家纺',
  ),
  350 => 
  array (
    'cat_id' => '350',
    'cat_name' => '床裙',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '350',
    'name' => '床裙',
  ),
  347 => 
  array (
    'cat_id' => '347',
    'cat_name' => '被褥',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '347',
    'name' => '被褥',
  ),
  344 => 
  array (
    'cat_id' => '344',
    'cat_name' => '枕芯',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '344',
    'name' => '枕芯',
  ),
  320 => 
  array (
    'cat_id' => '320',
    'cat_name' => '居家日用',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '14',
    'goods_num' => 0,
    'level' => 1,
    'id' => '320',
    'name' => '居家日用',
  ),
  357 => 
  array (
    'cat_id' => '357',
    'cat_name' => '洗漱用品',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '357',
    'name' => '洗漱用品',
  ),
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '净化除味',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '367',
    'name' => '净化除味',
  ),
  364 => 
  array (
    'cat_id' => '364',
    'cat_name' => '简易电脑桌',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '364',
    'name' => '简易电脑桌',
  ),
  361 => 
  array (
    'cat_id' => '361',
    'cat_name' => '纸巾盒',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '361',
    'name' => '纸巾盒',
  ),
  358 => 
  array (
    'cat_id' => '358',
    'cat_name' => '简易衣柜',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '358',
    'name' => '简易衣柜',
  ),
  355 => 
  array (
    'cat_id' => '355',
    'cat_name' => '洗衣篮',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '355',
    'name' => '洗衣篮',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '368',
    'name' => '清洁用品',
  ),
  365 => 
  array (
    'cat_id' => '365',
    'cat_name' => '挂钩',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '365',
    'name' => '挂钩',
  ),
  362 => 
  array (
    'cat_id' => '362',
    'cat_name' => '置物架',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '362',
    'name' => '置物架',
  ),
  359 => 
  array (
    'cat_id' => '359',
    'cat_name' => '衣架',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '359',
    'name' => '衣架',
  ),
  356 => 
  array (
    'cat_id' => '356',
    'cat_name' => '晾晒架',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '356',
    'name' => '晾晒架',
  ),
  366 => 
  array (
    'cat_id' => '366',
    'cat_name' => '烫衣板',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '366',
    'name' => '烫衣板',
  ),
  363 => 
  array (
    'cat_id' => '363',
    'cat_name' => '装饰镜/化妆镜',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '363',
    'name' => '装饰镜/化妆镜',
  ),
  360 => 
  array (
    'cat_id' => '360',
    'cat_name' => '家居收纳',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '360',
    'name' => '家居收纳',
  ),
  314 => 
  array (
    'cat_id' => '314',
    'cat_name' => '布艺织物',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 1,
    'id' => '314',
    'name' => '布艺织物',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '窗帘辅料/配件',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '373',
    'name' => '窗帘辅料/配件',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '布艺玩具',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '370',
    'name' => '布艺玩具',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '沙发套/垫',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '377',
    'name' => '沙发套/垫',
  ),
  374 => 
  array (
    'cat_id' => '374',
    'cat_name' => '地毯/地垫',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '374',
    'name' => '地毯/地垫',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '桌布',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '371',
    'name' => '桌布',
  ),
  378 => 
  array (
    'cat_id' => '378',
    'cat_name' => '防尘罩',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '378',
    'name' => '防尘罩',
  ),
  375 => 
  array (
    'cat_id' => '375',
    'cat_name' => '坐垫/靠垫',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '375',
    'name' => '坐垫/靠垫',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '桌旗',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '372',
    'name' => '桌旗',
  ),
  369 => 
  array (
    'cat_id' => '369',
    'cat_name' => '窗帘',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '369',
    'name' => '窗帘',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '轨道/罗马杆',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '379',
    'name' => '轨道/罗马杆',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '毛巾家纺',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '376',
    'name' => '毛巾家纺',
  ),
  319 => 
  array (
    'cat_id' => '319',
    'cat_name' => '家居饰品',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '17',
    'goods_num' => 0,
    'level' => 1,
    'id' => '319',
    'name' => '家居饰品',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '相框/照片墙',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '389',
    'name' => '相框/照片墙',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '红酒架',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '386',
    'name' => '红酒架',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '装饰',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '383',
    'name' => '装饰',
  ),
  396 => 
  array (
    'cat_id' => '396',
    'cat_name' => '装饰摆件',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '396',
    'name' => '装饰摆件',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '电话机',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '380',
    'name' => '电话机',
  ),
  393 => 
  array (
    'cat_id' => '393',
    'cat_name' => '烛台/蜡烛',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '393',
    'name' => '烛台/蜡烛',
  ),
  390 => 
  array (
    'cat_id' => '390',
    'cat_name' => '仿真花',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '390',
    'name' => '仿真花',
  ),
  387 => 
  array (
    'cat_id' => '387',
    'cat_name' => '创意公仔',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '387',
    'name' => '创意公仔',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '烟灰缸',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '384',
    'name' => '烟灰缸',
  ),
  381 => 
  array (
    'cat_id' => '381',
    'cat_name' => '壁饰/帖饰',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '381',
    'name' => '壁饰/帖饰',
  ),
  394 => 
  array (
    'cat_id' => '394',
    'cat_name' => '钟',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '394',
    'name' => '钟',
  ),
  391 => 
  array (
    'cat_id' => '391',
    'cat_name' => '花瓶/花盆',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '391',
    'name' => '花瓶/花盆',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '装饰画',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '388',
    'name' => '装饰画',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '风水摆件',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '385',
    'name' => '风水摆件',
  ),
  382 => 
  array (
    'cat_id' => '382',
    'cat_name' => '油画',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '382',
    'name' => '油画',
  ),
  395 => 
  array (
    'cat_id' => '395',
    'cat_name' => '首饰盒',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '395',
    'name' => '首饰盒',
  ),
  392 => 
  array (
    'cat_id' => '392',
    'cat_name' => '装饰花架',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '392',
    'name' => '装饰花架',
  ),
  315 => 
  array (
    'cat_id' => '315',
    'cat_name' => '厨房餐饮',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '315',
    'name' => '厨房餐饮',
  ),
  404 => 
  array (
    'cat_id' => '404',
    'cat_name' => '果盘/托物盘',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '404',
    'name' => '果盘/托物盘',
  ),
  401 => 
  array (
    'cat_id' => '401',
    'cat_name' => '刀具菜板',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '401',
    'name' => '刀具菜板',
  ),
  397 => 
  array (
    'cat_id' => '397',
    'cat_name' => '杯子',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '397',
    'name' => '杯子',
  ),
  405 => 
  array (
    'cat_id' => '405',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '405',
    'name' => '烹饪锅具',
  ),
  398 => 
  array (
    'cat_id' => '398',
    'cat_name' => '餐巾/餐垫',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '398',
    'name' => '餐巾/餐垫',
  ),
  402 => 
  array (
    'cat_id' => '402',
    'cat_name' => '铲勺',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '402',
    'name' => '铲勺',
  ),
  399 => 
  array (
    'cat_id' => '399',
    'cat_name' => '厨用收纳',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '399',
    'name' => '厨用收纳',
  ),
  403 => 
  array (
    'cat_id' => '403',
    'cat_name' => '茶具/咖啡具',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '403',
    'name' => '茶具/咖啡具',
  ),
  400 => 
  array (
    'cat_id' => '400',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '400',
    'name' => '餐具',
  ),
  529 => 
  array (
    'cat_id' => '529',
    'cat_name' => '业主专享',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '529',
    'name' => '业主专享',
  ),
  535 => 
  array (
    'cat_id' => '535',
    'cat_name' => '碧样板房',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '535',
    'name' => '碧样板房',
  ),
  571 => 
  array (
    'cat_id' => '571',
    'cat_name' => '华中区域',
    'measure_unit' => '',
    'parent_id' => '535',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '571',
    'name' => '华中区域',
  ),
  579 => 
  array (
    'cat_id' => '579',
    'cat_name' => '华南区域',
    'measure_unit' => '',
    'parent_id' => '535',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '579',
    'name' => '华南区域',
  ),
  578 => 
  array (
    'cat_id' => '578',
    'cat_name' => '华北区域',
    'measure_unit' => '',
    'parent_id' => '535',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '578',
    'name' => '华北区域',
  ),
  532 => 
  array (
    'cat_id' => '532',
    'cat_name' => '装修设计',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '532',
    'name' => '装修设计',
  ),
  544 => 
  array (
    'cat_id' => '544',
    'cat_name' => '软装设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '544',
    'name' => '软装设计',
  ),
  545 => 
  array (
    'cat_id' => '545',
    'cat_name' => '套餐设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '545',
    'name' => '套餐设计',
  ),
  546 => 
  array (
    'cat_id' => '546',
    'cat_name' => '家装设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '546',
    'name' => '家装设计',
  ),
  543 => 
  array (
    'cat_id' => '543',
    'cat_name' => '免费设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '543',
    'name' => '免费设计',
  ),
  547 => 
  array (
    'cat_id' => '547',
    'cat_name' => '商业空间设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '547',
    'name' => '商业空间设计',
  ),
  536 => 
  array (
    'cat_id' => '536',
    'cat_name' => '拎包入住',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '536',
    'name' => '拎包入住',
  ),
  561 => 
  array (
    'cat_id' => '561',
    'cat_name' => '软装套餐',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '561',
    'name' => '软装套餐',
  ),
  558 => 
  array (
    'cat_id' => '558',
    'cat_name' => '联排别墅',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '558',
    'name' => '联排别墅',
  ),
  562 => 
  array (
    'cat_id' => '562',
    'cat_name' => '办公空间',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '562',
    'name' => '办公空间',
  ),
  559 => 
  array (
    'cat_id' => '559',
    'cat_name' => '复式公寓',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '559',
    'name' => '复式公寓',
  ),
  556 => 
  array (
    'cat_id' => '556',
    'cat_name' => '单身公寓',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '556',
    'name' => '单身公寓',
  ),
  560 => 
  array (
    'cat_id' => '560',
    'cat_name' => '独栋别墅',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '560',
    'name' => '独栋别墅',
  ),
  557 => 
  array (
    'cat_id' => '557',
    'cat_name' => '平层公寓',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '557',
    'name' => '平层公寓',
  ),
  533 => 
  array (
    'cat_id' => '533',
    'cat_name' => '装修风格',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '533',
    'name' => '装修风格',
  ),
  555 => 
  array (
    'cat_id' => '555',
    'cat_name' => '新中式风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '555',
    'name' => '新中式风格',
  ),
  551 => 
  array (
    'cat_id' => '551',
    'cat_name' => '东南亚风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '551',
    'name' => '东南亚风格',
  ),
  548 => 
  array (
    'cat_id' => '548',
    'cat_name' => '美式乡村风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '548',
    'name' => '美式乡村风格',
  ),
  552 => 
  array (
    'cat_id' => '552',
    'cat_name' => '日韩风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '552',
    'name' => '日韩风格',
  ),
  549 => 
  array (
    'cat_id' => '549',
    'cat_name' => '古典欧式风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '549',
    'name' => '古典欧式风格',
  ),
  553 => 
  array (
    'cat_id' => '553',
    'cat_name' => '新古典风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '553',
    'name' => '新古典风格',
  ),
  550 => 
  array (
    'cat_id' => '550',
    'cat_name' => '地中海式风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '550',
    'name' => '地中海式风格',
  ),
  572 => 
  array (
    'cat_id' => '572',
    'cat_name' => '现代简约风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '572',
    'name' => '现代简约风格',
  ),
  534 => 
  array (
    'cat_id' => '534',
    'cat_name' => '本地装修',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '534',
    'name' => '本地装修',
  ),
  570 => 
  array (
    'cat_id' => '570',
    'cat_name' => '湖北',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '570',
    'name' => '湖北',
  ),
  567 => 
  array (
    'cat_id' => '567',
    'cat_name' => '北京',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '567',
    'name' => '北京',
  ),
  568 => 
  array (
    'cat_id' => '568',
    'cat_name' => '上海',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '568',
    'name' => '上海',
  ),
  569 => 
  array (
    'cat_id' => '569',
    'cat_name' => '四川',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '569',
    'name' => '四川',
  ),
  531 => 
  array (
    'cat_id' => '531',
    'cat_name' => '碧桂园区域',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '531',
    'name' => '碧桂园区域',
  ),
  541 => 
  array (
    'cat_id' => '541',
    'cat_name' => '碧桂园华南区',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '541',
    'name' => '碧桂园华南区',
  ),
  538 => 
  array (
    'cat_id' => '538',
    'cat_name' => '碧桂园华北区',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '538',
    'name' => '碧桂园华北区',
  ),
  542 => 
  array (
    'cat_id' => '542',
    'cat_name' => '碧桂园华中区',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '542',
    'name' => '碧桂园华中区',
  ),
  539 => 
  array (
    'cat_id' => '539',
    'cat_name' => '碧桂园·金沙滩',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '539',
    'name' => '碧桂园·金沙滩',
  ),
  540 => 
  array (
    'cat_id' => '540',
    'cat_name' => '碧桂园·十里银滩',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '540',
    'name' => '碧桂园·十里银滩',
  ),
  505 => 
  array (
    'cat_id' => '505',
    'cat_name' => '安装服务',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '505',
    'name' => '安装服务',
  ),
  334 => 
  array (
    'cat_id' => '334',
    'cat_name' => '安装服务',
    'measure_unit' => '套',
    'parent_id' => '505',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '334',
    'name' => '安装服务',
  ),
  337 => 
  array (
    'cat_id' => '337',
    'cat_name' => '门安装',
    'measure_unit' => '',
    'parent_id' => '334',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '337',
    'name' => '门安装',
  ),
  335 => 
  array (
    'cat_id' => '335',
    'cat_name' => '卫浴安装',
    'measure_unit' => '',
    'parent_id' => '334',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '335',
    'name' => '卫浴安装',
  ),
  336 => 
  array (
    'cat_id' => '336',
    'cat_name' => '地板安装',
    'measure_unit' => '',
    'parent_id' => '334',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '336',
    'name' => '地板安装',
  ),
);
?>