<?php
$data = array (
  0 => 
  array (
    'cat_id' => '325',
    'cat_name' => '家具城',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '326',
    'cat_name' => '家居城',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '503',
    'cat_name' => '办公家具',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '502',
    'cat_name' => '户外家具',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '507',
    'cat_name' => '定制家具',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '506',
    'cat_name' => '墙纸地板',
    'measure_unit' => 'm2',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '515',
    'cat_name' => '定制木门',
    'measure_unit' => '樘',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '514',
    'cat_name' => '瓷砖建材',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '311',
    'cat_name' => '家纺家饰',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '529',
    'cat_name' => '业主专享',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '505',
    'cat_name' => '安装服务',
    'measure_unit' => '套',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '228',
    'cat_name' => '穿衣镜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  12 => 
  array (
    'cat_id' => '74',
    'cat_name' => '衣柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '63',
  ),
  13 => 
  array (
    'cat_id' => '23',
    'cat_name' => '床',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '99',
  ),
  14 => 
  array (
    'cat_id' => '88',
    'cat_name' => '床尾凳',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  15 => 
  array (
    'cat_id' => '226',
    'cat_name' => '定制衣柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '24',
    'cat_name' => '床垫',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
  ),
  17 => 
  array (
    'cat_id' => '227',
    'cat_name' => '斗柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  18 => 
  array (
    'cat_id' => '69',
    'cat_name' => '梳妆台',
    'measure_unit' => '张',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
  ),
  19 => 
  array (
    'cat_id' => '25',
    'cat_name' => '床头柜',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  20 => 
  array (
    'cat_id' => '231',
    'cat_name' => '电视柜',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '39',
  ),
  21 => 
  array (
    'cat_id' => '235',
    'cat_name' => '真皮沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  22 => 
  array (
    'cat_id' => '232',
    'cat_name' => '酒柜',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  23 => 
  array (
    'cat_id' => '230',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
  ),
  24 => 
  array (
    'cat_id' => '238',
    'cat_name' => '休闲椅',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  25 => 
  array (
    'cat_id' => '233',
    'cat_name' => '茶几',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '62',
  ),
  26 => 
  array (
    'cat_id' => '237',
    'cat_name' => '布艺沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '48',
  ),
  27 => 
  array (
    'cat_id' => '239',
    'cat_name' => '转角沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  28 => 
  array (
    'cat_id' => '234',
    'cat_name' => '鞋柜',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  29 => 
  array (
    'cat_id' => '236',
    'cat_name' => '组合沙发',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '245',
    'cat_name' => '圆餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '242',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '247',
    'cat_name' => '折叠餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '246',
    'cat_name' => '长餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '243',
    'cat_name' => '餐边柜',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  35 => 
  array (
    'cat_id' => '244',
    'cat_name' => '餐桌椅套餐',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  36 => 
  array (
    'cat_id' => '241',
    'cat_name' => '餐桌',
    'measure_unit' => '',
    'parent_id' => '240',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
  ),
  37 => 
  array (
    'cat_id' => '251',
    'cat_name' => '实木书桌',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '252',
    'cat_name' => '书柜/书架',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  39 => 
  array (
    'cat_id' => '249',
    'cat_name' => '书桌/工作台',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '253',
    'cat_name' => '书椅/转椅',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '250',
    'cat_name' => '转角书桌',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '254',
    'cat_name' => '书房套装',
    'measure_unit' => '',
    'parent_id' => '248',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '260',
    'cat_name' => '儿童桌',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '258',
    'cat_name' => '儿童床头柜',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '256',
    'cat_name' => '儿童床',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  46 => 
  array (
    'cat_id' => '262',
    'cat_name' => '双层床',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  47 => 
  array (
    'cat_id' => '259',
    'cat_name' => '儿童衣柜',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '261',
    'cat_name' => '儿童椅',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '257',
    'cat_name' => '儿童床垫',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '266',
    'cat_name' => '吊篮',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '264',
    'cat_name' => '户外桌椅',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '269',
    'cat_name' => '摇椅',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '268',
    'cat_name' => '沙滩床',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '267',
    'cat_name' => '户外秋千',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '265',
    'cat_name' => '遮阳伞',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '272',
    'cat_name' => '办公桌',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  57 => 
  array (
    'cat_id' => '271',
    'cat_name' => '办公沙发',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '276',
    'cat_name' => '办公椅',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '273',
    'cat_name' => '会议桌',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '274',
    'cat_name' => '大班台',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '275',
    'cat_name' => '文件柜',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '282',
    'cat_name' => '落地灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '279',
    'cat_name' => '壁灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  64 => 
  array (
    'cat_id' => '283',
    'cat_name' => 'LED/光源',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '280',
    'cat_name' => '吸顶灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '63',
  ),
  66 => 
  array (
    'cat_id' => '281',
    'cat_name' => '台灯',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '79',
  ),
  67 => 
  array (
    'cat_id' => '278',
    'cat_name' => '吊顶',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '40',
  ),
  68 => 
  array (
    'cat_id' => '288',
    'cat_name' => '电视',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '285',
    'cat_name' => '冰箱',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '289',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '286',
    'cat_name' => '洗衣机',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '290',
    'cat_name' => '吸油烟机',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '287',
    'cat_name' => '空调',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '291',
    'cat_name' => '净水设备',
    'measure_unit' => '',
    'parent_id' => '284',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '296',
    'cat_name' => '花洒',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '35',
  ),
  76 => 
  array (
    'cat_id' => '293',
    'cat_name' => '浴室柜',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '56',
  ),
  77 => 
  array (
    'cat_id' => '297',
    'cat_name' => '座便器',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '58',
  ),
  78 => 
  array (
    'cat_id' => '295',
    'cat_name' => '浴缸',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  79 => 
  array (
    'cat_id' => '321',
    'cat_name' => '淋浴房',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  80 => 
  array (
    'cat_id' => '299',
    'cat_name' => '厨盆/水槽',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
  ),
  81 => 
  array (
    'cat_id' => '300',
    'cat_name' => '厨房挂件',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  82 => 
  array (
    'cat_id' => '577',
    'cat_name' => 'PVC墙纸',
    'measure_unit' => '',
    'parent_id' => '301',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '576',
    'cat_name' => '无纺布墙纸',
    'measure_unit' => '',
    'parent_id' => '301',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '302',
    'cat_name' => '墙布',
    'measure_unit' => '',
    'parent_id' => '301',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '27',
  ),
  85 => 
  array (
    'cat_id' => '308',
    'cat_name' => '开关插座',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  86 => 
  array (
    'cat_id' => '309',
    'cat_name' => '锁具',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '310',
    'cat_name' => '门吸',
    'measure_unit' => '',
    'parent_id' => '307',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '312',
    'cat_name' => '床上用品',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '16',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '320',
    'cat_name' => '居家日用',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '14',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '314',
    'cat_name' => '布艺织物',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '11',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '319',
    'cat_name' => '家居饰品',
    'measure_unit' => '套',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '17',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '315',
    'cat_name' => '厨房餐饮',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '341',
    'cat_name' => '特惠套餐',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '354',
    'cat_name' => '夏凉被',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '351',
    'cat_name' => '枕套',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '348',
    'cat_name' => '被套',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '345',
    'cat_name' => '毛毯',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '342',
    'cat_name' => '床幔/蚊帐',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '339',
    'cat_name' => '床品件套',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '352',
    'cat_name' => '凉席',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '349',
    'cat_name' => '床笠',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '346',
    'cat_name' => '床褥',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '343',
    'cat_name' => '被芯',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '340',
    'cat_name' => '记忆枕',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '353',
    'cat_name' => '婚庆家纺',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '350',
    'cat_name' => '床裙',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '347',
    'cat_name' => '被褥',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '344',
    'cat_name' => '枕芯',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '373',
    'cat_name' => '窗帘辅料/配件',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '370',
    'cat_name' => '布艺玩具',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '377',
    'cat_name' => '沙发套/垫',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '374',
    'cat_name' => '地毯/地垫',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '371',
    'cat_name' => '桌布',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '378',
    'cat_name' => '防尘罩',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '375',
    'cat_name' => '坐垫/靠垫',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '372',
    'cat_name' => '桌旗',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '369',
    'cat_name' => '窗帘',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '379',
    'cat_name' => '轨道/罗马杆',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '376',
    'cat_name' => '毛巾家纺',
    'measure_unit' => '',
    'parent_id' => '314',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '404',
    'cat_name' => '果盘/托物盘',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '401',
    'cat_name' => '刀具菜板',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '397',
    'cat_name' => '杯子',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '405',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '398',
    'cat_name' => '餐巾/餐垫',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '402',
    'cat_name' => '铲勺',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '399',
    'cat_name' => '厨用收纳',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '403',
    'cat_name' => '茶具/咖啡具',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '400',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '315',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '389',
    'cat_name' => '相框/照片墙',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '386',
    'cat_name' => '红酒架',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '383',
    'cat_name' => '装饰',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '396',
    'cat_name' => '装饰摆件',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '380',
    'cat_name' => '电话机',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '393',
    'cat_name' => '烛台/蜡烛',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '390',
    'cat_name' => '仿真花',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '387',
    'cat_name' => '创意公仔',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '384',
    'cat_name' => '烟灰缸',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '381',
    'cat_name' => '壁饰/帖饰',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '394',
    'cat_name' => '钟',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '391',
    'cat_name' => '花瓶/花盆',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '388',
    'cat_name' => '装饰画',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '385',
    'cat_name' => '风水摆件',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '382',
    'cat_name' => '油画',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '395',
    'cat_name' => '首饰盒',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '392',
    'cat_name' => '装饰花架',
    'measure_unit' => '',
    'parent_id' => '319',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '357',
    'cat_name' => '洗漱用品',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '367',
    'cat_name' => '净化除味',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '364',
    'cat_name' => '简易电脑桌',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '361',
    'cat_name' => '纸巾盒',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '358',
    'cat_name' => '简易衣柜',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '355',
    'cat_name' => '洗衣篮',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '368',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '365',
    'cat_name' => '挂钩',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '362',
    'cat_name' => '置物架',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '359',
    'cat_name' => '衣架',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '356',
    'cat_name' => '晾晒架',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '366',
    'cat_name' => '烫衣板',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '363',
    'cat_name' => '装饰镜/化妆镜',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '360',
    'cat_name' => '家居收纳',
    'measure_unit' => '',
    'parent_id' => '320',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '4',
    'cat_name' => '卧室',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => '84',
  ),
  161 => 
  array (
    'cat_id' => '229',
    'cat_name' => '客厅',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => '1',
  ),
  162 => 
  array (
    'cat_id' => '240',
    'cat_name' => '餐厅',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '248',
    'cat_name' => '书房',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '255',
    'cat_name' => '儿童房',
    'measure_unit' => '套',
    'parent_id' => '325',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '277',
    'cat_name' => '灯饰照明',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '298',
    'cat_name' => '厨房用品',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '292',
    'cat_name' => '卫浴用品',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => '1',
  ),
  168 => 
  array (
    'cat_id' => '284',
    'cat_name' => '生活电器',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '525',
    'cat_name' => '油漆类',
    'measure_unit' => '套',
    'parent_id' => '326',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '337',
    'cat_name' => '门安装',
    'measure_unit' => '',
    'parent_id' => '334',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '335',
    'cat_name' => '卫浴安装',
    'measure_unit' => '',
    'parent_id' => '334',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '336',
    'cat_name' => '地板安装',
    'measure_unit' => '',
    'parent_id' => '334',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '263',
    'cat_name' => '户外家具',
    'measure_unit' => '套',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '270',
    'cat_name' => '办公家具',
    'measure_unit' => '套',
    'parent_id' => '503',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '307',
    'cat_name' => '家装五金',
    'measure_unit' => '套',
    'parent_id' => '504',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '334',
    'cat_name' => '安装服务',
    'measure_unit' => '套',
    'parent_id' => '505',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '301',
    'cat_name' => '墙面',
    'measure_unit' => '套',
    'parent_id' => '506',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '573',
    'cat_name' => '地面',
    'measure_unit' => '',
    'parent_id' => '506',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '508',
    'cat_name' => '定制家具',
    'measure_unit' => '套',
    'parent_id' => '507',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '512',
    'cat_name' => '定制酒柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '509',
    'cat_name' => '定制橱柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '511',
    'cat_name' => '定制鞋柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '513',
    'cat_name' => '定制储物柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '510',
    'cat_name' => '定制衣柜',
    'measure_unit' => '套',
    'parent_id' => '508',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '520',
    'cat_name' => '瓷砖类目',
    'measure_unit' => 'm2',
    'parent_id' => '514',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '504',
    'cat_name' => '五金配件',
    'measure_unit' => '套',
    'parent_id' => '515',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '530',
    'cat_name' => '钛金移门',
    'measure_unit' => '套',
    'parent_id' => '515',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '516',
    'cat_name' => '套装门',
    'measure_unit' => '樘',
    'parent_id' => '515',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '518',
    'cat_name' => '复合门',
    'measure_unit' => '樘',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  190 => 
  array (
    'cat_id' => '517',
    'cat_name' => '实木门',
    'measure_unit' => '樘',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '519',
    'cat_name' => '工艺门',
    'measure_unit' => '樘',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  192 => 
  array (
    'cat_id' => '524',
    'cat_name' => '阳台瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '522',
    'cat_name' => '厨房瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '521',
    'cat_name' => '客厅瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '523',
    'cat_name' => '厕所瓷砖',
    'measure_unit' => 'm2',
    'parent_id' => '520',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  196 => 
  array (
    'cat_id' => '528',
    'cat_name' => '乳胶漆配件',
    'measure_unit' => '套',
    'parent_id' => '525',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  197 => 
  array (
    'cat_id' => '526',
    'cat_name' => '乳胶漆',
    'measure_unit' => '套',
    'parent_id' => '525',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  198 => 
  array (
    'cat_id' => '527',
    'cat_name' => '木器漆',
    'measure_unit' => '套',
    'parent_id' => '525',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '535',
    'cat_name' => '碧样板房',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '532',
    'cat_name' => '装修设计',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '536',
    'cat_name' => '拎包入住',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  202 => 
  array (
    'cat_id' => '533',
    'cat_name' => '装修风格',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  203 => 
  array (
    'cat_id' => '534',
    'cat_name' => '本地装修',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  204 => 
  array (
    'cat_id' => '531',
    'cat_name' => '碧桂园区域',
    'measure_unit' => '',
    'parent_id' => '529',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  205 => 
  array (
    'cat_id' => '541',
    'cat_name' => '碧桂园华南区',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  206 => 
  array (
    'cat_id' => '538',
    'cat_name' => '碧桂园华北区',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  207 => 
  array (
    'cat_id' => '542',
    'cat_name' => '碧桂园华中区',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  208 => 
  array (
    'cat_id' => '539',
    'cat_name' => '碧桂园·金沙滩',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  209 => 
  array (
    'cat_id' => '540',
    'cat_name' => '碧桂园·十里银滩',
    'measure_unit' => '',
    'parent_id' => '531',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  210 => 
  array (
    'cat_id' => '544',
    'cat_name' => '软装设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  211 => 
  array (
    'cat_id' => '545',
    'cat_name' => '套餐设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  212 => 
  array (
    'cat_id' => '546',
    'cat_name' => '家装设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  213 => 
  array (
    'cat_id' => '543',
    'cat_name' => '免费设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  214 => 
  array (
    'cat_id' => '547',
    'cat_name' => '商业空间设计',
    'measure_unit' => '',
    'parent_id' => '532',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  215 => 
  array (
    'cat_id' => '555',
    'cat_name' => '新中式风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  216 => 
  array (
    'cat_id' => '551',
    'cat_name' => '东南亚风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  217 => 
  array (
    'cat_id' => '548',
    'cat_name' => '美式乡村风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  218 => 
  array (
    'cat_id' => '552',
    'cat_name' => '日韩风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  219 => 
  array (
    'cat_id' => '549',
    'cat_name' => '古典欧式风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  220 => 
  array (
    'cat_id' => '553',
    'cat_name' => '新古典风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  221 => 
  array (
    'cat_id' => '550',
    'cat_name' => '地中海式风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  222 => 
  array (
    'cat_id' => '572',
    'cat_name' => '现代简约风格',
    'measure_unit' => '',
    'parent_id' => '533',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  223 => 
  array (
    'cat_id' => '570',
    'cat_name' => '湖北',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  224 => 
  array (
    'cat_id' => '567',
    'cat_name' => '北京',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  225 => 
  array (
    'cat_id' => '568',
    'cat_name' => '上海',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  226 => 
  array (
    'cat_id' => '569',
    'cat_name' => '四川',
    'measure_unit' => '',
    'parent_id' => '534',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  227 => 
  array (
    'cat_id' => '571',
    'cat_name' => '华中区域',
    'measure_unit' => '',
    'parent_id' => '535',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  228 => 
  array (
    'cat_id' => '579',
    'cat_name' => '华南区域',
    'measure_unit' => '',
    'parent_id' => '535',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  229 => 
  array (
    'cat_id' => '578',
    'cat_name' => '华北区域',
    'measure_unit' => '',
    'parent_id' => '535',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  230 => 
  array (
    'cat_id' => '561',
    'cat_name' => '软装套餐',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  231 => 
  array (
    'cat_id' => '558',
    'cat_name' => '联排别墅',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  232 => 
  array (
    'cat_id' => '562',
    'cat_name' => '办公空间',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  233 => 
  array (
    'cat_id' => '559',
    'cat_name' => '复式公寓',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  234 => 
  array (
    'cat_id' => '556',
    'cat_name' => '单身公寓',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  235 => 
  array (
    'cat_id' => '560',
    'cat_name' => '独栋别墅',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  236 => 
  array (
    'cat_id' => '557',
    'cat_name' => '平层公寓',
    'measure_unit' => '',
    'parent_id' => '536',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  237 => 
  array (
    'cat_id' => '574',
    'cat_name' => '实木地板',
    'measure_unit' => '',
    'parent_id' => '573',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  238 => 
  array (
    'cat_id' => '575',
    'cat_name' => '强化复合地板',
    'measure_unit' => '',
    'parent_id' => '573',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  239 => 
  array (
    'cat_id' => '303',
    'cat_name' => '强化实木地板',
    'measure_unit' => '',
    'parent_id' => '573',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '90',
  ),
);
?>